// ─── Color token interface ────────────────────────────────────────────────────
export interface AppColors {
  // Fondos
  background: string;
  card: string;
  cardSecondary: string;
  inputBg: string;
  // Bordes
  border: string;
  borderSubtle: string;
  // Texto
  textPrimary: string;
  textSecondary: string;
  textTertiary: string;
  textInverse: string;
  // Marca
  primary: string;
  primaryLight: string;
  primaryDark: string;
  primaryText: string;
  // Semánticos
  income: string;
  incomeLight: string;
  incomeText: string;
  expense: string;
  expenseLight: string;
  expenseText: string;
  warning: string;
  warningLight: string;
  warningText: string;
  ai: string;
  aiLight: string;
  aiText: string;
  // Navegación
  tabBar: string;
  tabBarBorder: string;
  tabActive: string;
  tabInactive: string;
  tabActiveBg: string;
  // Header
  headerBg: string;
  headerText: string;
  headerSubtext: string;
  headerIcon: string;
  headerXpTrack: string;
  headerXpFill: string;
  // Estados
  success: string;
  successLight: string;
  danger: string;
  dangerLight: string;
  // Overlay
  overlay: string;
  overlayLight: string;
  // Misc
  skeleton: string;
  skeletonHighlight: string;
  divider: string;
  statusBar: 'dark-content' | 'light-content';
}

// ─── Light palette (aligned with THEME tokens) ────────────────────────────────
export const LIGHT_COLORS: AppColors = {
  background:        '#F8F7FF',
  card:              '#FFFFFF',
  cardSecondary:     '#F4F3F8',
  inputBg:           '#F4F3F8',
  border:            '#E5E7EB',
  borderSubtle:      '#F4F3F8',
  textPrimary:       '#111827',
  textSecondary:     '#6B7280',
  textTertiary:      '#9CA3AF',
  textInverse:       '#FFFFFF',
  primary:           '#6156E8',
  primaryLight:      '#EEF0FF',
  primaryDark:       '#4A3FD4',
  primaryText:       '#3730A3',
  income:            '#1D9E75',
  incomeLight:       '#D1FAE5',
  incomeText:        '#065F46',
  expense:           '#F55B5B',
  expenseLight:      '#FEE2E2',
  expenseText:       '#991B1B',
  warning:           '#F59E0B',
  warningLight:      '#FEF3C7',
  warningText:       '#92400E',
  ai:                '#8B5CF6',
  aiLight:           '#EDE9FE',
  aiText:            '#5B21B6',
  tabBar:            '#FFFFFF',
  tabBarBorder:      '#E5E7EB',
  tabActive:         '#6156E8',
  tabInactive:       '#9CA3AF',
  tabActiveBg:       '#EEF0FF',
  headerBg:          '#6156E8',
  headerText:        '#FFFFFF',
  headerSubtext:     'rgba(255,255,255,0.75)',
  headerIcon:        '#FFFFFF',
  headerXpTrack:     'rgba(255,255,255,0.2)',
  headerXpFill:      '#FFFFFF',
  success:           '#1D9E75',
  successLight:      '#D1FAE5',
  danger:            '#F55B5B',
  dangerLight:       '#FEE2E2',
  overlay:           'rgba(0,0,0,0.5)',
  overlayLight:      'rgba(0,0,0,0.08)',
  skeleton:          '#F4F3F8',
  skeletonHighlight: '#E5E7EB',
  divider:           '#F4F3F8',
  statusBar:         'dark-content',
};

// ─── Dark palette ──────────────────────────────────────────────────────────────
export const DARK_COLORS: AppColors = {
  background:        '#0F0F11',
  card:              '#1C1C1F',
  cardSecondary:     '#252528',
  inputBg:           '#2A2A2E',
  border:            '#2E2E33',
  borderSubtle:      '#252528',
  textPrimary:       '#F4F4F5',
  textSecondary:     '#A1A1AA',
  textTertiary:      '#71717A',
  textInverse:       '#111827',
  primary:           '#818CF8',
  primaryLight:      '#1E1B4B',
  primaryDark:       '#6366F1',
  primaryText:       '#C7D2FE',
  income:            '#34D399',
  incomeLight:       '#064E3B',
  incomeText:        '#6EE7B7',
  expense:           '#F87171',
  expenseLight:      '#450A0A',
  expenseText:       '#FCA5A5',
  warning:           '#FBBF24',
  warningLight:      '#451A03',
  warningText:       '#FDE68A',
  ai:                '#A78BFA',
  aiLight:           '#2E1065',
  aiText:            '#DDD6FE',
  tabBar:            '#1C1C1F',
  tabBarBorder:      '#2E2E33',
  tabActive:         '#818CF8',
  tabInactive:       '#71717A',
  tabActiveBg:       '#1E1B4B',
  headerBg:          '#312E81',
  headerText:        '#FFFFFF',
  headerSubtext:     'rgba(255,255,255,0.6)',
  headerIcon:        '#FFFFFF',
  headerXpTrack:     'rgba(255,255,255,0.15)',
  headerXpFill:      '#A5B4FC',
  success:           '#34D399',
  successLight:      '#064E3B',
  danger:            '#F87171',
  dangerLight:       '#450A0A',
  overlay:           'rgba(0,0,0,0.7)',
  overlayLight:      'rgba(0,0,0,0.2)',
  skeleton:          '#2A2A2E',
  skeletonHighlight: '#3F3F46',
  divider:           '#2E2E33',
  statusBar:         'light-content',
};

// Backward compatibility
export const COLORS = LIGHT_COLORS;
